# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ai_devs

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: my-job
    runs-on: self-hosted

    steps:
 # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
     # - run: bun index.ts
     # - run: bun run build
